#!/bin/bash

# Regex for a conventional commit.
conventional_commit_regex="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|test|style)(\([a-z \-]+\))?!?: .+$"
merge_or_rebase_commit="^Merge.|^Rebase."

# Getting the commit message and branch name
commit_message=$(cat "$1")

# Checking the message.
if [[ "$commit_message" =~ $conventional_commit_regex || "$commit_message" =~ $merge_or_rebase_commit ]]; then
    # In case of unconventional commit.
    echo -e "\e[32mCommit message meets conventional commit standards...\e[0m"
    exit 0
fi

echo -e "\e[31mThe commit message does not meet the conventional commit standard\e[0m"
echo "An example of a valid message is:"
echo "feat: add the 'remember me' button"
echo "More details on README"
exit 1
